package com.linuxea.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("article_with_kind", "id", ArticleWithKind.class);
		arp.addMapping("article_with_tag", "id", ArticleWithTag.class);
		arp.addMapping("kind", "id", Kind.class);
		arp.addMapping("login_list", "id", LoginList.class);
		arp.addMapping("tag", "id", Tag.class);
		arp.addMapping("user", "id", User.class);
	}
}

