package com.linuxea.model;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends com.linuxea.model.BaseArticle<Article> {
    public static final Article dao = new Article().dao();
}
