package com.linuxea.model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleWithKind extends BaseArticleWithKind<ArticleWithKind> {
    public static final ArticleWithKind dao = new ArticleWithKind().dao();
}
