package com.linuxea.model;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleWithTag extends BaseArticleWithTag<ArticleWithTag> {
    public static final ArticleWithTag dao = new ArticleWithTag().dao();
}
