package com.linuxea.model;

import com.linuxea.model.base.BaseArticleWithKind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleWithKind extends BaseArticleWithKind<ArticleWithKind> {
	public static final ArticleWithKind dao = new ArticleWithKind().dao();
}
