package com.linuxea.model;

import com.linuxea.model.base.BaseBlackList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BlackList extends BaseBlackList<BlackList> {
	public static final BlackList dao = new BlackList().dao();
}
