package com.linuxea.model;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kind extends com.linuxea.model.base.BaseKind<Kind> {
    public static final Kind dao = new Kind().dao();
}
