package com.linuxea.model;

import com.linuxea.model.base.BaseLoginList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginList extends BaseLoginList<LoginList> {
	public static final LoginList dao = new LoginList().dao();
}
