package com.linuxea.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticleWithTag<M extends BaseArticleWithTag<M>> extends Model<M> implements IBean {
	
	public java.lang.String getId() {
		return getStr("id");
	}
	
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getArticleId() {
		return getStr("article_id");
	}
	
	public void setArticleId(java.lang.String articleId) {
		set("article_id", articleId);
	}
	
	public java.lang.String getTagId() {
		return getStr("tag_id");
	}
	
	public void setTagId(java.lang.String tagId) {
		set("tag_id", tagId);
	}
	
}
